### ISSUE TITLE
Matlab version of PhononSED

### ISSUE THREAD

**Issue by JWCheys** [delton137/PhononSED#1]
As shwon in README of PhononSED, a newer version has been developed in Matlab. So, I'd like to friendly ask you to share your Matlab version. Thank you very much.
Best regards.

**Comment by delton137** [comment]
A newer version of the visualization code (for plotting the peaks) was written in Matlab. Gaurav Kumar wrote it. Basically I handed off this project to him.  I don't think he rewrote the SED calculation in matlab because Fortran is much faster and it's written to be parallelized over nodes on a cluster.  You can email him at gkumar1@umd.edu to ask him.

**Comment by JWCheys** [comment]
Thank you very much for your reply.
Best regard.

**Comment by delton137** [comment]
No problem. If you use our code or find it otherwise useful, please cite this work: 

G. Kumar, F. G. VanGessel, D. C. Elton, and P. W. Chung. “[Phonon Lifetimes and Thermal Conductivity of the Molecular Crystal α-RDX](https://www.cambridge.org/core/journals/mrs-advances/article/phonon-lifetimes-and-thermal-conductivity-of-the-molecular-crystal-rdx/14B1FC4424D8C4A659589DC535DBB5A7)”, _MRS Advances_, **4**, 2191 (2019)
